Faile to fetch
WildCodeSchool/reims-0218-gyvit pull request #169
Opened 2018-07-16 13:29 UTC by PhiTarte

2018-07-16 13:30 UTC, PhiTarte commented
now all login succeding

2018-07-16 16:06 UTC, dadtmt requested changes

2018-07-16 16:06 UTC, dadtmt commented on package.json
>      "luxon": "^1.2.1",
you don't need dotenv

2018-07-17 09:29 UTC, dadtmt approved these changes

2018-07-17 09:29 UTC, merged